# For more info on HTTP files go to https://aka.ms/vs/httpfile

@hostname=localhost
@port=5116

# Company APIS
## POST /api/Companies
## GET /api/Companies
## GET /api/Companies/{companyID}
## GET /api/Companies?pageSize=2&pageIndex=3
## PUT /api/Companies/{companyID}
## DELETE /api/Companies/{companyID} ( Delete employees uner this company in same time )


## AC1 Create Company API 
POST https://{{hostname}}:{{port}}/api/companies
Content-Type: application/json; charset=utf-8

{
  "name": "Google"
}

## Response:
### Case1:  Company Created Success, Return Company created with Status Created( 201 )
### Case2:  Company Name Exsiting, Return 400 Bad request
### Case3:  Other Bad Reqeust ( Request Body Not Valid )

######################################################################################

## AC2 Get All Compaines
GET https://{{hostname}}:{{port}}/api/companies

### Response: OK 200 with List of Companes

######################################################################################

## AC3 Get Company By ID
GET https://{{hostname}}:{{port}}/api/Companies/{companyID}

### Response: 
### Case1: OK 200 with The Company Found
### Case2: 404 Company NOT Found

## AC4 GET Companies with Paging 
GET https://{{hostname}}:{{port}}/api/Companies?pageSize=2&pageIndex=3
### Response: OK 200 with List of Companes

######################################################################################

## AC5 Update Company 
PUT https://{{hostname}}:{{port}}/api/Companies/{companyID}
Content-Type: application/json; charset=utf-8

{
  "name": Google
}
### Response: 
### Case1: Sucess, 204 NO Content
### Case2: 404 Company NOT Found

######################################################################################

## AC6 Add Employee To Company 
Post https://{{hostname}}:{{port}}/api/companies/{companyId}/employees
Content-Type: application/json; charset=utf-8

{
  "name": AA,
  "salary": 4000
}
### Response: 
### Case1: Sucess, 201 Created with Employee
### Case2: 404 not found

##################################################################################
####

## AC7 Delete Employee by CompanyId and EmployeeId
DELETE https://{{hostname}}:{{port}}/api/companies/{companyId}/employees/{employeeId}
 
### Response:
### Case1: Sucess, 204 NO Content
### Case2: 404 not found

##################################################################################
####

## AC8 Get list of Employee By Company Id
Get https://{{hostname}}:{{port}}/api/companies/{companyId}/employees
 
### Response:
### Case1: OK 200 with List of Employees of the company
### Case2: 404 not found

##################################################################################
####

## AC9 update employee by EmployeeId and CompanyId
PUT https://{{hostname}}:{{port}}/api/companies/{companyId}/employees/{employeeId}
 
{
  "name": "AA"
  "salary": 3000
}
### Response:
### Case1: Sucess, 204 NO Content
### Case2: 404 not found

##################################################################################

## AC10 Delete Company by CompanyId (with employees being deleted)
DELETE https://{{hostname}}:{{port}}/api/companies/{companyId}

### Response:
### Case1: Sucess, 204 NO Content
### Case2: 404 not found

##################################################################################